# Generated by Django 5.1.3 on 2024-12-01 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('select_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='GroceryStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('select_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('select_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_items', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryStoreItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('select_id', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('common_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.commonitem')),
                ('store_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.grocerystore')),
            ],
        ),
    ]
